name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main

  workflow_dispatch:
  
jobs:
  build_macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: install dependencies
        run: |
          brew install SDL2
      - name: build
        run:
          ./build.sh
