name: CI
on: [push, pull_request, workflow_dispatch]
  
jobs:
  build_macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: install dependencies
        run: |
          brew install SDL2
      - name: build
        run:
          ./build.sh
      - name: compress and archive
        run:
          zip -r ca-framework build
      - name: upload artifacts
        uses: actions/upload-artifact@v2
        with: 
          name: macos-artifact
          path: ca-framework.zip
