name: CI
on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build_macos:
    runs-on: actions/checkout@v3
    steps:
      - name: install dependencies
        run: |
          brew install SDL2
          brew install clang
      - name: build
        run:
          ./build.sh
