name: CI
on: [push, pull_request, workflow_dispatch]
  
jobs:
  build_macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: install dependencies
        run: |
          brew install SDL2
      - name: build
        run:
          make
      - name: compress and archive
        run:
          zip -r ca-framework bin
      - name: upload artifacts
        uses: actions/upload-artifact@v2
        with: 
          name: macos-artifact
          path: ca-framework.zip
  build_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-go@v3
      - name: build
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          build.bat
      - name: upload artifacts
        uses: actions/upload-artifact@v2
        with: 
          name: windows-artifact
          path: bin
