name: CI
on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

  workflow_dispatch:
  
jobs:
  build_macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: install dependencies
        run: |
          brew install SDL2
          brew install clang
      - name: build
        run:
          ./build.sh
